name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: phpize
    - name: Install Aeron
      run: |
        git clone --branch 1.38.2 --depth 1 https://github.com/real-logic/aeron.git
        mkdir --parents aeron/cppbuild/Debug
        cd aeron/cppbuild/Debug
        cmake -DCMAKE_BUILD_TYPE=Debug ../..
        cmake --build . --clean-first --parallel 2
        sudo cmake --install .
    - name: Compile extension
      run: |
        phpize
        ./configure
        make
    - name: Run tests
      run: |
        TEST_PHP_ARGS="-q" make test
