# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4', '8.0', '8.1', '8.2']
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: phpize
    - name: Install Aeron
      run: |
        git clone --branch 1.38.2 --depth 1 https://github.com/real-logic/aeron.git
        mkdir --parents aeron/cppbuild/Debug
        cd aeron/cppbuild/Debug
        cmake -DCMAKE_BUILD_TYPE=Debug ../..
        cmake --build . --clean-first --parallel 2
        sudo cmake --install .
    - name: Compile extension
      run: |
        phpize
        ./configure
        make
    - name: Run tests
      run: make test
